highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4001
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Jie ZHU's Resume
name: Jie ZHU
email: 18100895X@connect.polyu.hk
#website: github.io/sustain
#website_full: https://jekyller.github.io/sustain
WeChat: zj13982687008 
Facebook: Zhu Jie
tel: +86 13982687008
#tel_full: tel:+440000000000
#google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address:
  street: 92 West Dazhi Street, Nan Gang District
  postcode: 150001
  city: Harbin
  country: China
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
